### PR TITLE
Tauhid621/fetch policy error

### LINKED ISSUE #45: Actions reports success when ARM API return error
Hello,
I have noticed the action report success status when ARM API call fails (at least for assignment).
No conditionals are used for the action.

Bellow two examples:

`
Failed to get policy with id /providers/Microsoft.Management/managementGroups/test-spgi-terraform/providers/Microsoft.Authorization/policyAssignments/Append_NSG_if_missing-4ca69cc5-3a14-4614-9d17-04e0ca2cee70, path config-files/policy/policies/Append_NSG_for_MG/assign.Test-SPGI-Terraform.Append_NSG_if_missing.json. Error : {"code":"InvalidPolicyAssignmentName","message":"The policy assignment name 'Append_NSG_if_missing-4ca69cc5-3a14-4614-9d17-04e0ca2cee70' is invalid. The policy assignment name length must not exceed '24' characters."}
`

image
image

### PR DESCRIPTION
**Pull request by tauhid621**
Fail Action when there is an error while getting policies from Azure.

Screenshot 2021-04-08 at 4 04 09 PM

Fixed #45

### CODE REVIEW

File: src/azure/policyHelper.ts [hunk 1]
```diff
@@ -89,6 +89,11 @@ export async function getAllPolicyRequests(): Promise<PolicyRequest[]> {
         }
       }
     }
+
+    // There were errors while getting policies. We will not proceed further.
+    if (allPolicyDetails.length != policyRequests.length) {
```
Comment (ajinkya599) [inline src/azure/policyHelper.ts:94]: Shouldn't the behaviour be the following -
Try applying other policies and report this error in the logs/summary. The overall action status should be failed.

Should we discuss this with the PMs once?

**Review by ajinkya599 — APPROVED** [review]
LGTM 🚀

File: src/azure/policyHelper.ts (hunk 1 above)
Comment (tauhid621) [reply src/azure/policyHelper.ts:94]: Discussed with PM.
We might end up in a bad state if we try to skip applying some policies.
